apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
        - name: ftp-server
          image: your-ftp-image:tag
          ports:
            - containerPort: 21
          env:
            - name: FTP_USER
              value: admin
            - name: FTP_PASS
              value: admin
