apiVersion: v1
kind: Service
metadata:
  name: ftp-service
spec:
  selector:
    app: ftp
  ports:
    - name: ftp
      protocol: TCP
      port: 21
      targetPort: 21
      nodePort: 30021
    - name: passive-min-port
      protocol: TCP
      port: 30080
      targetPort: minport
      nodePort: 30080
    - name: passive-max-port
      protocol: TCP
      port: 30081
      targetPort: maxport
      nodePort: 30081
  type: NodePort
